### PR TITLE
Add CPU halt state

### PR DESCRIPTION
**Pull request by Hnefi**

### CODE REVIEW

**Comment by sid1994** [comment]
Travis shows compilation errors.

**Comment by Hnefi** [comment]
> Travis shows compilation errors.

This is because this branch depends on a change to libqflex. (https://github.com/parsa-epfl/libqflex/pull/8)

Once that is merged, i will force Travis to rerun, and it will compile

**Comment by sid1994** [comment]
Oh, wait.
This also has synchronization related changes.
Do you want to commit them as well?

Also, maybe squash or refactor your commits to get rid of the special formatting commit.

**Comment by Hnefi** [comment]
> Oh, wait.
> This also has synchronization related changes.
> Do you want to commit them as well?
> 
> Also, maybe squash or refactor your commits to get rid of the special formatting commit.

All changes to ExclusiveMonitorAction have been reverted, so squashing will not change this file at all and also remove the format. That ok?

**Comment by sid1994** [comment]
Ok!

**Pull request merged**
